import Head from "next/head";
import Layout from "../components/layout/Layout";
import styles from "../components/Book/BookRequest.module.css";
import SuccessAlert from "../components/Book/SuccessAlert";
import { useState } from "react";

export default function BookRequest() {
  const [isSuccess, setIsSuccess] = useState(false);
  const [enteredInput, setEnteredInput] = useState("");

  const inputChangeHandler = (event) => {
    setEnteredInput(event.target.value);
  };

  const submitHandler = (event) => {
    event.preventDefault();

    setIsSuccess(true);
    setEnteredInput("");
  };

  return (
    <div>
      <Head>
        <title>Audio Book</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="grid grid-cols-12 gap-4 mx-14 my-8">
        <div className="col-span-5">
          <div className="flex justify-center items-center">
            <img src="/images/book_request.png" alt="Logo" />
          </div>
        </div>
        <div className="col-span-7">
          <form action="" method="post" onSubmit={submitHandler}>
            <h3 className={`${styles.h3} mb-2`}>
              Vui lòng nhập tựa sách bạn muốn yêu cầu.
            </h3>
            {isSuccess && <SuccessAlert />}
            <div className="form-group mb-4">
              <textarea
                id="about"
                name="about"
                rows={3}
                className={`${styles.textarea} shadow-sm focus:ring-indigo-500 focus:border-indigo-500 mt-1 block w-full sm:text-sm border border-gray-300 rounded-md`}
                placeholder="Nhập càng nhiều càng tốt nhé ..."
                value={enteredInput}
                onChange={inputChangeHandler}
              />
            </div>
            <button
              type="submit"
              className={`${styles.button} bg-transparent hover:bg-blue-500 text-blue-700 font-semibold hover:text-white py-2 px-4 border border-blue-500 hover:border-transparent rounded`}
            >
              Gửi
            </button>
          </form>
        </div>
      </div>
    </div>
  );
}

//Layout
BookRequest.layout = Layout;
