import Head from "next/head";
import Layout from "../components/layout/Layout";
// import RadioGroupRating from "../components/RadioGroupRating";
// import SelectOtherProps from "../components/SelectOtherProps";
// import Button from "@mui/material/Button";
// import Image from "next/image";
import HomeContent from "../components/HomeContent/HomeContent";
import useWindowSize from '../utils/useWindowSize'

export default function Home() {
  let windowSize = useWindowSize()
  return (
    <div>
      <Head>
        <title>Audio Book</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeContent open={true} windowSize={windowSize}></HomeContent>
      {/* Main */}
      {/* <div className="flex justify-center items-center">
        <img src="https://www.w3schools.com/w3css/img_lights.jpg" alt="" />
      </div> */}
      {/* <div>
        <div className="flex justify-center items-center py-2">
          <RadioGroupRating />
        </div>
        <div className="flex justify-center items-center py-2">
          <SelectOtherProps />
        </div>
      </div> */}
      {/* <Button variant="contained">Hello World</Button> */}
    </div>
  );
}

//Layout
Home.layout = Layout;
