import Head from "next/head";
import Layout from "../components/layout/Layout";
// import RadioGroupRating from "../components/RadioGroupRating";
// import SelectOtherProps from "../components/SelectOtherProps";
// import Button from "@mui/material/Button";
// import Image from "next/image";
import HomeContent from "../components/HomeContent/HomeContent";
import useWindowSize from "../utils/useWindowSize";

export default function Home() {
  let windowSize = useWindowSize();
  return (
    <div>
      <Head>
        <title>Audio Book</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeContent open={true} windowSize={windowSize}></HomeContent>
    </div>
  );
}

//Layout
Home.layout = Layout;
